stages:
  - build
  - test
  - deploy

variables:
  DOCKER_HUB_USERNAME: <your_username>
  DOCKER_HUB_PASSWORD: <your_password>

build:
  stage: build
  script:
    - docker build -t $DOCKER_HUB_USERNAME/myapp .
    - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
    - docker push $DOCKER_HUB_USERNAME/myapp

test:
  stage: test
  script:
    - echo "Running tests..."

deploy:
  stage: deploy
  script:
    - kubectl apply -f deployment.yaml
